### ISSUE TITLE
Переименовать файлы "repo" в "storage" в соответствии с новыми названиями классов

### ISSUE THREAD

**Issue by CleanJoin** [CleanJoin/RestChat#11]
* использовать git mv

**Comment by min0ru** [comment]
Использовать "git mv" для переименования!
![image](https://user-images.githubusercontent.com/1928457/152407220-575ec38d-3873-4b68-a809-426c68a06f32.png)

**Comment by CleanJoin** [comment]
Переименовал файлы -> 8583c47d8dca51584ca6829b1a4417ed1d6c7251
