### ISSUE TITLE
Сделать вспомогательные функции приватными (называния в нижнем регистре)

### ISSUE THREAD

**Issue by min0ru** [CleanJoin/RestChat#3]
Функции, которые не являются открытыми методами класса (не объявлены в интерфейсе) должны быть приватными, так как работа с конкретной реализацией класса ведется только через интерфейс.

Пример.

ReceivelastIDSession -> receiveLastSessionId
RemoveIndexSession -> removeSessionByIndex

**Comment by CleanJoin** [comment]
Изменил -> a42aa51860446c8af0ab122256df061d18bdf63c
