### ISSUE TITLE
Использовать консистентное название методов get, delete, вместо "receive" и "remove"

### ISSUE THREAD

**Issue by min0ru** [CleanJoin/RestChat#4]
Методы, извлекающие какие-либо данные должны называться с "get", а не "receive". Receive - это "принять" (из внешнего источника).

Договорились, что для методов, удаляющих что-либо мы используем "delete", вместо "remove".

**Comment by CleanJoin** [comment]
Выполнил-> a42aa51860446c8af0ab122256df061d18bdf63c
