### ISSUE TITLE
Переименовать интерфейсы, классы и методы в соответствии со структурой классов в проекте miro

### ISSUE THREAD

**Issue by min0ru** [CleanJoin/RestChat#5]
Переименовать интерфейсы, классы и методы в соответствии со структурой классов в проекте miro miro (https://miro.com/app/board/uXjVORposyg=/)

**Comment by CleanJoin** [comment]
MessageStorage -> d531a562cb80010a239c2dd304fc6f8773523dcc
SessionStorage -> 601167d706834757cae99f2401ff119254d5e1e7

**Comment by CleanJoin** [comment]
UserStorage -> dd8a0d9a53f6784fe692d95f4f303fdc6f80d7ea
